# borders and messages
set -g pane-border-style         "fg=#261c17"
set -g pane-active-border-style  "fg=#ca9395"
set -g message-style             "bg=#ca9395,fg=#12080a"
set -g message-command-style     "bg=#ca9395,fg=#12080a"

# statusline base
set -g status on
set -g status-interval 1
set -g status-position bottom
set -g status-justify left
set -g status-left-length 80
set -g status-right-length 160
set -g status-style "bg=default,fg=#ca9395"

# left bubble: session
set -g status-left "#[fg=#ca9395]#[bg=#ca9395]#[fg=#12080a]#[bold]   #S #[nobold]#[fg=#ca9395]#[bg=default] "

# right bubbles: prefix, git branch, host, time
set -g status-right '#{?client_prefix,#[fg=#4f2d29]#[bg=#4f2d29]#[fg=#f0dde1]#[bold] ⏽ PREFIX #[nobold]#[fg=#4f2d29]#[bg=default] ,}#[fg=#4f2d29]#[bg=#4f2d29]#[fg=#f0dde1]  #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "-") #[fg=#4f2d29]#[bg=default] #[fg=#261c17]#[bg=#261c17]#[fg=#f0dde1] #H #[fg=#261c17]#[bg=default] #[fg=#12080a]#[bg=#12080a]#[fg=#b97074] %Y-%m-%d %H:%M #[fg=#12080a]#[bg=default]'

# window tabs
set -g window-status-separator ""
set -g window-status-format         " #[fg=#261c17]#I #[fg=#f0dde1]#W "
set -g window-status-current-format "#[fg=#ca9395]#[bg=#ca9395]#[fg=#12080a]#[bold] #I: #W #[nobold]#[fg=#ca9395]#[bg=default]"
