# core
experimental-features = nix-command flakes
auto-optimise-store = true
warn-dirty = false

# performance
max-jobs = auto
cores = 0
connect-timeout = 5
http-connections = 50

# sandboxing & isolation
sandbox = true
sandbox-fallback = false
restrict-eval = false

# trust model
trusted-users = root ashgw
allowed-users = *

# garbage collection
keep-outputs = true
keep-derivations = true

# networking
fallback = true
builders-use-substitutes = true

# logging / UX
log-lines = 50
show-trace = true

# security hygiene
require-sigs = true
accept-flake-config = true

