[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Neovim" },
]

play = [
	{ run = 'mpv "$@"', orphan = true, desc = "MPV" }
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, desc = "Zathura" }
]

[open]
rules = [
	{ name = "*.pdf", use = "pdf" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
	{ mime = "image/*", use = "play" }
]

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
image_filter    = "lanczos3"
image_quality   = 75
# Kitty is the only terminal that handles previews perfectly, Alacritty will need a fallback.
